# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terminado.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_terminado(object):
    def setupUi(self, terminado):
        terminado.setObjectName("terminado")
        terminado.resize(417, 532)
        self.centralwidget = QtWidgets.QWidget(terminado)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 230, 91, 41))
        self.label.setStyleSheet("QLabel{\n"
"    font-size: 20px;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 280, 101, 41))
        self.label_2.setStyleSheet("QLabel{\n"
"    font-size: 20px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 240, 291, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"    font-size: 17px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 290, 291, 31))
        self.label_4.setStyleSheet("QLabel{\n"
"    font-size: 17px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, -150, 341, 371))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 330, 141, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        terminado.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(terminado)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 417, 18))
        self.menubar.setObjectName("menubar")
        terminado.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(terminado)
        self.statusbar.setObjectName("statusbar")
        terminado.setStatusBar(self.statusbar)

        self.retranslateUi(terminado)
        QtCore.QMetaObject.connectSlotsByName(terminado)

    def retranslateUi(self, terminado):
        _translate = QtCore.QCoreApplication.translate
        terminado.setWindowTitle(_translate("terminado", "MainWindow"))
        self.label.setText(_translate("terminado", "Usuario:"))
        self.label_2.setText(_translate("terminado", "Password:"))
        self.label_5.setText(_translate("terminado", "<html><head/><body><p><img src=\":/newPrefix/Downloads/Logo-Lobo-PNG-removebg-preview.png\"/></p></body></html>"))
        self.pushButton.setText(_translate("terminado", "Clique"))
