# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perfil_conta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logado(object):
    def setupUi(self, logado):
        logado.setObjectName("logado")
        logado.resize(434, 583)
        logado.setStyleSheet("QMenuBar{\n"
"    background-color: black;\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(logado)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 240, 291, 151))
        self.label.setStyleSheet("font-size: 30px;\n"
"")
        self.label.setObjectName("label")
        logado.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(logado)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 26))
        self.menubar.setObjectName("menubar")
        self.menuPerfil = QtWidgets.QMenu(self.menubar)
        self.menuPerfil.setObjectName("menuPerfil")
        logado.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(logado)
        self.statusbar.setObjectName("statusbar")
        logado.setStatusBar(self.statusbar)
        self.actionConta = QtWidgets.QAction(logado)
        self.actionConta.setObjectName("actionConta")
        self.menuPerfil.addAction(self.actionConta)
        self.menubar.addAction(self.menuPerfil.menuAction())

        self.retranslateUi(logado)
        QtCore.QMetaObject.connectSlotsByName(logado)

    def retranslateUi(self, logado):
        _translate = QtCore.QCoreApplication.translate
        logado.setWindowTitle(_translate("logado", "MainWindow"))
        self.label.setText(_translate("logado", "Logado"))
        self.menuPerfil.setTitle(_translate("logado", "Perfil"))
        self.actionConta.setText(_translate("logado", "Conta"))
