# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 150, 441, 51))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    \n"
"    padding-left: 10px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 220, 441, 51))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    \n"
"    padding-left: 10px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 290, 441, 51))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    \n"
"    padding-left: 10px;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 360, 261, 61))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 251, 51))
        self.label.setStyleSheet("QLabel{\n"
"    font-size: 20px;\n"
"\n"
"    color: red;\n"
"\n"
"}")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Gmail"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Senha-Confirm"))
        self.pushButton.setText(_translate("MainWindow", "Registrar"))
        self.label.setText(_translate("MainWindow", "Registrar"))
